* Contributing
** Stack
   The blog is powered by [[https://github.com/theiceshelf/firn][Firn]] and [[https://clojure.org][Clojure]], using [[https://orgmode.org][Org-mode's syntax]] for
   pure contents, and [[https://github.com/weavejester/hiccup][Hiccup's syntax]] for rendering HTML.

** Repository Architecture
   - The ~public~ folder contains the ~*.org~ articles that are published;
   - The ~dev~ folder contains WIP articles and notes that are not yet
     published, or only in the scope of this repository;
   - The ~private~ folder is gitignored for very primitive content.

** Development
   - Once Firn is installed, ~cd~ into the ~public~ folder and ~firn dev~
   - Open ~localhost:4000~ to see the index

** Notes on the ~_firn~ folder's content.
   - There are both french and english articles. The default layout
     maintains a localized dictionnary for the blog's skeleton.
   - To render an ~*.org~ file in a specific language, add
     ~#+LANGUAGE: fr~ (for example) at the very top of the file.
   - There are both a dark and light theme.
