#+TITLE: The coumpound interests of learning
#+DATE_CREATED: <2021-02-01>
#+DATE_UPDATED: <2021-02-09 17:06>
#+FIRN_UNDER: "Random notes"

When you learn *productivity tips*, there is hope for *long term ROI* on
the time you invest in learning. If you know *the power of coumpound
interests*, then you can infer that *the soonest you know something,
the more value it generates over time*.

Investing 1 hour today to learn something that will make you win 12
seconds per working day saves you 1 minute per week so almost an hour
per year for the rest of your career ! Well, I know what you mean, 1
hour saved per year won't change your life. But guess what happens if you
invest one hour per week to perfect your workflow ? You literally
save years, I am not kidding, do the math !

Let's compare someone that doesn't invest in perfecting their
workflow and someone who does. Let's say both are given a
40-years-long task given their current skills (working 7 hours per
day, 5 days per week, 47 weeks per year (5 weeks off per year)). The
one that doesn't perfect its workflow will take 40 years to make it.
The other invests 1 hour per week in learning, and for each hour
invested, he wins 12 seconds over his workmate. *It will take him
9.5 years less than his non-learning workmate to do just as much*.

A one hour learning session for saving only 12 seconds spared each
following days doesn't seem much, but it could make you retire 10
years earlier. That's why *one must learn*.
