#+TITLE: Lydéric's Digital Garden
#+SUB-TITLE: Good Luck !
#+DATE_CREATED: <2021-01-30 sam.>
#+DATE_UPDATED: <2021-03-05 10:33>

Hi, welcome on my digital garden ! Here, you'll find most of the notes I
take, useful links I have read, conceptual thoughts, and many other
ideas about business, IT, personal development and science.

If you [[https://en.wikipedia.org/wiki/Fear_of_missing_out][FOMO]], be sure to follow me on [[https://twitter.com/lyderichti59][Twitter]], I'll share my blog
content and retweet funny memes.

Sharing gives many collective opportunities, and I'm fearly convinced that
 [[https://www.youtube.com/watch?v=1THE-vyhk4A]["Apes together strong"]].
 So, feel free to reach out one way or the other.

You can start by clicking on those links :
- [[file:introducing-myself.org][Who am I ?]]
- [[file:compound-interests-of-learning.org][Benefits of Learning]]
- [[file:targeted-knowledge.org][Targeted knowledge]]
- [[file:local-first-software.org][Local-First Software (French)]]


The first release of this braindump has been made on the 31st
January 2021. It is still under active development. *So, stay tuned,
more content is about to come soon.*

-----

/PS/ : This *digital garden* is written with [[https://www.gnu.org/software/emacs/][Emacs]] using [[https://www.orgmode.org/][org files]], and
brought to the web with [[https://firn.theiceshelf.com/][Firn]] using [[https://clojure.org/][Clojure]].
