#+TITLE: Hey, I am Lydéric
#+DATE_CREATED: <2021-01-31>
#+DATE_UPDATED: <2021-02-09 21:23>
#+FIRN_UNDER: "Lydéric's Digital Garden"

Hello world !

I'm *Lydéric Dutillieux*, I'm 22 years old at time of writing, and I'm
passionate about technology, business, investment, personal
development and science.

There are many things I would like to achieve in my life, including
working full time on solving most of the world's challenging problems.
# I guess that starting with [[https://en.wikipedia.org/wiki/FIRE_movement][FIRE (Financial Independance, Retire Early)]]
# would allow me to do this regardless of my time's ROI.

For now, I'm mainly earning a living as a *Freelance Software Engineer*,
with [[https://www.origenial.fr/][Origénial]] and investing most of my time in developping a
platform, called [[https://www.ponceleo.com/][Ponceleo]], that aims at *expanding the lifespan of people's goods*
and *fighting against planned obsolescence*.

I love sharing, that's why I have been maintaining this blog about my
thoughts on our world. It should not be seen as a "push-only" blog,
but rather as an asynchronous way of communicating with everyone. I
love discussing, so feel free to reach out and *let's talk about
whatever you want.*
